const themeCorpus = {
  name: "Theme",
  locale: "en-US",
  data: [
    {
      intent: "theme.change",
      utterances: [
        "change theme",
        "change theme to @theme",
        "can you change theme to @theme",
        "please change the theme to @theme",
        "turn on @theme theme",
        "turn on @theme",
      ],
      answers: [],
    },
  ],
  entities: {
    theme: {
      options: {
        dark: [
          "dark",
          "dark mode",
          "dark theme",
          "darkmode",
          "darktheme",
          "dark-mode",
          "dark-theme",
        ],
        light: [
          "light",
          "light mode",
          "light theme",
          "lightmode",
          "lighttheme",
          "light-mode",
          "light-theme",
        ],
        cupcake: [
          "cupcake",
          "cupcake theme",
          "cupcake-theme",
          "cupcake-mode",
          "cup",
        ],
        bumblebee: ["bumblebee"],
        emerald: ["emerald"],
        corporate: ["corporate"],
        synthwave: ["synthwave"],
        retro: ["retro"],
        cyberpunk: ["cyberpunk"],
        valentine: ["valentine"],
        halloween: ["halloween"],
        garden: ["garden"],
        forest: ["forest"],
        aqua: ["aqua"],
        lofi: ["lofi"],
        pastel: ["pastel"],
        fantasy: ["fantasy"],
        wireframe: ["wireframe"],
        black: ["black"],
        luxury: ["luxury"],
        dracula: ["dracula"],
        cmyk: ["cmyk"],
        autumn: ["autumn"],
        business: ["business"],
        acid: ["acid"],
        lemonade: ["lemonade"],
        night: ["night"],
        coffee: ["coffee"],
        winter: ["winter"],
      },
    },
  },
};

export default themeCorpus;
