- name: Use coturiv/setup-ionic
  uses: coturiv/setup-ionic@v1
  with:
    java-version: 8
- name: Use coturiv/setup-ionic
  uses: coturiv/setup-ionic@v1
  with:
    cordova-version: 8

- name: Build
  run: |
    ionic cordova build android --prod
