name: Build and deploy
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup ionic and capacitor
        run: |
          npm i -g cordova @ionic/cli @capacitor/cli yarn ionic
          
      - name: Install node modules
        run: yarn

      - name: Build app for android
        run: |
          ionic capacitor copy android 
          cd android 
          gradlew assembleDebug 
          cd ..
          find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/| - \1/"
          
        
