name: Build and deploy
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup java with ionic
        uses: coturiv/setup-ionic@v1
        with:
          java-version: 8

      - name: Setup cordova with ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build
        run: |
          ionic capacitor copy android 
          cd android
          gradlew assembleDebug
          cd ..
