---
name: "Pre release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup ionic and capacitor
        run: |
          npm i -g @ionic/cli @capacitor/cli yarn
          
      - name: Install node modules
        run: yarn

      - name: Build app for android
        env:
          REACT_APP_YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          CI=false
          yarn build
          npx cap sync android
          ionic capacitor update
          ionic capacitor copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          cd ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "v1.*.* release"
          files: |
            android/app/build/outputs/apk/release/app-release-unsigned.apk
            android/app/build/outputs/apk/debug/app-debug.apk