---
name: "Pre release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup ionic and capacitor
        run: |
          npm i -g @ionic/cli @capacitor/cli yarn
          
      - name: Install node modules
        run: yarn

      - name: Build app for android
        env:
          REACT_APP_YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          CI=false
          yarn build
          npx cap sync android
          ionic capacitor update
          ionic capacitor copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          cd ..

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          tag-prefix: "v"
          skip-git-pull: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: true
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          files: |
            android/app/build/outputs/apk/release/app-release-unsigned.apk
            android/app/build/outputs/apk/debug/app-debug.apk
            CHANGELOG.md